### ISSUE TITLE
how to access "reversed"

### ISSUE THREAD

**Issue by uknowmeright** [createwithflow/FlowCommoniOS#28]
We are updating our repos and noticed that the "reversed" Timeline property is no longer available in the latest update. 

Is there a recommended way to play an animation in reverse?

Example of usage:

```
var clockcheck: ClockcheckTimeline!
clockcheck = ClockcheckTimeline(view: clockbegin, duration: 0.5)
clockcheck.reversed.reset()
clockcheck.reversed.play()
```

Thank you!

**Comment by C4Framework** [comment]
Hey, apologies for the delay.

The `reversed` property hasn't been taken out of the repo... 

You can see it here: https://github.com/createwithflow/FlowCommoniOS/blob/4ae4d5e6221865180853ae052595f85305149303/Sources/FlowCommoniOSFiles/Timeline.swift#L151

The best way to play an animation in reverse is to store the reversed timeline like so: 

`let reversed = timeline.reversed()`

Then, you can call:

`reversed.play()`

-

You should check out our iOS Custom Button export, it has a great approach for handling exactly the scenario you're working on.

**Comment by C4Framework** [comment]
Closing as there hasn't been any activity here in a while.
Feel free to reopen if this isn't resolved.
