### ISSUE TITLE
Animation disappears on iPhone 12 pro, iPhone mini

### ISSUE THREAD

**Issue by uknowmeright** [createwithflow/FlowCommoniOS#32]
The attached animation does not stay on the final frame after playing through once. After it plays the animation goes blank and you can only see the view's background. It appears this is only an issue for us on iPhone 12 pro and iPhone mini models. When testing with an iPhone 8 the animation behaves correctly. 

We have tried setting the offset to the animation's duration on the didReset, didPause and didStop funcs of the TimelineDelegate but this seems to have no effect. 

Any ideas why this might be happening? 

Here is a sample of the code we use to play the animation:

```
    @IBOutlet private weak var checkMarkAnimation: CheckmarkgreenView!

    var timeline: CheckmarkTimeline!

    override public func viewDidLoad() {
        super.viewDidLoad()
        timeline = CheckmarkTimeline(view: checkMarkAnimation, duration: 1.0)
    }

    override public func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if viewModel?.cancelled == false {
            timeline.delegate = self
            timeline.play()
        }
    }
```
[checkmark-short.zip](https://github.com/createwithflow/FlowCommoniOS/files/9551987/checkmark-short.zip)

**Comment by C4Framework** [comment]
Hey @uknowmeright,

Thanks for sending the Xcode project.

We have a small update to FlowCommon coming that addresses this issue. 

We're not fully sure why things changed, but the current iOS export used to work across all iOS and tvOS devices. 

That said, here are the three files we've updated (but not yet released):

[updatedFlowCommonFiles.zip](https://github.com/createwithflow/FlowCommoniOS/files/9552410/updatedFlowCommonFiles.zip)

Small changes to Timeline, Animation and CAKeyframeAnimation+Extension.

Please drop these in place of files exported from Flow, and in our next release these will be automatically exported.

T

**Comment by C4Framework** [comment]
Also, I put those files into your xcode project and it remedied the behaviour for me.

**Comment by C4Framework** [comment]
Here is a working export as well:

[iOS.zip](https://github.com/createwithflow/FlowCommoniOS/files/9552599/iOS.zip)
